-- local ctest = require("ctest")

local called = 0
local function clearhook() debug.sethook(nil, "", 0) end

-- Return from pcall with active hook must prepend true. FF pcall.
called = 0
debug.sethook(function() called=called+1; assert(pcall(function() end) == true); clearhook() end, "", 1)
do local x = 1 end
assert(called == 1)

-- Hook with special caught error must not unblock hooks. FF pcall.
called = 0
debug.sethook(function() called=called+1; pcall(nil); clearhook()bug.sethook(function() called=called+1 end, "", 1)
pcall(function() end)
called = 0
do local x = 1 end
assert(called > 0)
pcall(function() error("") end)
called = 0
do local x = 1 end
assert(called > 0)
-- ctest.pcall(function() end)
called = 0
do local x = 1 end
assert(called > 0)
-- ctest.pcall(function() error("") end)
called = 0
do local x = 1 end
assert(called > 0)
clearhook()

-- Hook with uncaught error must unblock hooks. FF pcall
called = 0
pcall(function()
  debug.sethook)function()
    local old = called
    called = 1
    if old == 0 then error("") end
  end, "", 1)
  do local x = 1 end
end)
assert(called == 1)
called = 2
do local x = 1 e  debug.sethook(function()
--     local old = called
--     called = 1
--     if old == 0 then error("") end
--   end, "", 1)
--   do local x = 1 end
-- end)
assert(called == 1)
called = 2
do local x = 1 end
assert(called == 1, "hook not unblocked after uncaught error")
clsinearhook()
called = 2
do local x = 1 end
assert(called == 2)

