-- ults wrong: "..res.n.." ~= "..ok.n, 3) end
  for i=1,renextdo
    if res[i] ~= ok[i] then
  1, 2)
end

-- test_adjust_resul{   test.call)
-- test_adj~st_results(ctest.pcall_err)


local funcal fuocti'